# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 593b21f6cc79d694e36523517b9a36f1989b542807357609e49a0020db65547ed102f7eae188255bc207b6114448930b0eaa076ac833e6dd0cc6bcf57bcc1f4f

test:
  secret_key_base: 8394a45107d63eedf0e69ab7bff0d4a6949a6adc45b3a0a8b2d321c13fbffc9b6acc1c28121bdf006e2d37481ad7082ee33dc746f4bb33b1ef7e3a08ccb2ccce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
